/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BenefitsForCooperators: typeof import('./src/components/index/BenefitsForCooperators.vue')['default']
    BenefitsForSuppliers: typeof import('./src/components/index/BenefitsForSuppliers.vue')['default']
    CardsSlider: typeof import('./src/components/CardsSlider.vue')['default']
    ChallengesForCooperators: typeof import('./src/components/index/ChallengesForCooperators.vue')['default']
    ChallengesForSuppliers: typeof import('./src/components/index/ChallengesForSuppliers.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ImagesSlider: typeof import('./src/components/ImagesSlider.vue')['default']
    ListWithImage: typeof import('./src/components/ListWithImage.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    LogoWithText: typeof import('./src/components/LogoWithText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopImagesSlider: typeof import('./src/components/index/TopImagesSlider.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    TwoColorTitle: typeof import('./src/components/TwoColorTitle.vue')['default']
  }
}
